name: Update File Periodically

on:
  schedule:
    - cron: '0 22 * * *'

permissions:
  contents: write
jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update file
        run: |
          rm images.txt
          touch images.txt

          wget -q -O - http://download.proxmox.com/images/ | grep -o -E 'href="[^"#]*\.dat"' | sed -e 's/^href="//' -e 's/"$//' | sort | uniq | while read file;
          do
            wget -q -O- http://download.proxmox.com/images/$file >> images.txt
            echo >> images.txt
          done;

          cat images.txt

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add images.txt
          git commit -m "Update images.txt" || echo "No changes"
          git push || true
